/* CRIAÇÃO DE TABELAS DA CAMADA GOLD (DIMENSIONAL) */

------ DIMENSÃO DEPUTADO ------
CREATE TABLE gold.dim_deputado 
(
  "sk_deputado" int generated by default as identity not null,
  "id_deputado" int not null,
  "nm_depudado" text not null,
  "sg_sexo" text not null,
  "dt_nascimento" date not null,
  "sg_uf" text not null,
  "ds_escolaridade" text not null,
  "sg_partido" text not null,
  "ds_lider_partido" text not null,
  "ds_situacao" text not null,
  "ds_condicao_eleitoral" text not null,
  "cd_legislatura" int not null,
  "dt_inicio_legislatura" date not null,
  "dt_fim_legislatura" date not null,
  "dt_inicio_vigencia" date not null default current_date,
  "dt_fim_vigencia" date not null default '9999-12-31',
  "dh_ingestao" timestamp without time zone not null default current_timestamp,
  constraint dim_deputado_pkey primary key (sk_deputado)
) TABLESPACE pg_default;

/* INSERE REGISTROS DE CHAVE SUBSTITUTA DE DIMENSÃO */
INSERT INTO gold.dim_deputado
("sk_deputado" , "id_deputado", "nm_depudado", "sg_sexo", "dt_nascimento", "sg_uf", "ds_escolaridade" , "sg_partido", "ds_lider_partido", "ds_situacao", "ds_condicao_eleitoral", "cd_legislatura", "dt_inicio_legislatura", "dt_fim_legislatura", "dt_inicio_vigencia", "dt_fim_vigencia", "dh_ingestao")
VALUES
(-1, -1, 'NÃO INFORMADO', 'N/I', '9999-12-31', 'N/I', 'NÃO INFORMADO', 'N/I', 'NÃO INFORMADO', 'NÃO INFORMADO', 'NÃO INFORMADO', -1, '9999-12-31', '9999-12-31', current_date, '9999-12-31', current_timestamp),
(-3, -3, 'NÃO SE APLICA', 'N/A', '9999-12-31', 'N/A', 'NÃO SE APLICA', 'N/A', 'NÃO SE APLICA', 'NÃO SE APLICA', 'NÃO SE APLICA', -3, '9999-12-31', '9999-12-31', current_date, '9999-12-31', current_timestamp)
----------------------

------- DIMENSÃO ORGÃO -------
CREATE TABLE gold.dim_orgao
(
  "sk_orgao" int generated by default as identity not null,
  "id_orgao" int not null,
  "sg_orgao" text not null,
  "nm_orgao" text not null,
  "ds_apelido_orgao" text not null,
  "ds_tipo_orgao" text not null,
  "dt_inicio_vigencia" date not null default current_date,
  "dt_fim_vigencia" date not null default '9999-12-31',
  "dh_ingestao" timestamp without time zone not null default current_timestamp,
  constraint dim_orgao_pkey primary key (sk_orgao)
) TABLESPACE pg_default;

/* INSERE REGISTROS DE CHAVE SUBSTITUTA DE DIMENSÃO */
INSERT INTO gold.dim_orgao
("sk_orgao" , "id_orgao", "sg_orgao", "nm_orgao", "ds_apelido_orgao", "ds_tipo_orgao", "dt_inicio_vigencia" , "dt_fim_vigencia", "dh_ingestao")
VALUES
(-1, -1, 'N/I', 'NÃO INFORMADO', 'NÃO INFORMADO', 'NÃO INFORMADO', current_date, '9999-12-31', current_timestamp),
(-3, -3, 'N/A', 'NÃO SE APLICA', 'NÃO SE APLICA', 'NÃO SE APLICA', current_date, '9999-12-31', current_timestamp)
---------------------

------- DIMENSÃO EVENTO -------
CREATE TABLE gold.dim_evento 
(
  "sk_evento" int generated by default as identity not null,
  "id_evento" int not null,
  "ds_tipo_evento" text not null,
  "ds_situacao" text not null,
  "dt_inicio_vigencia" date not null default current_date,
  "dt_fim_vigencia" date not null default '9999-12-31',
  "dh_ingestao" timestamp without time zone not null default current_timestamp,
  constraint dim_evento_pkey primary key (sk_evento)
) TABLESPACE pg_default;

/* INSERE REGISTROS DE CHAVE SUBSTITUTA DE DIMENSÃO */
INSERT INTO gold.dim_evento
("sk_evento" , "id_evento", "ds_tipo_evento", "ds_situacao", "dt_inicio_vigencia" , "dt_fim_vigencia", "dh_ingestao")
VALUES
(-1, -1, 'NÃO INFORMADO', 'NÃO INFORMADO', current_date, '9999-12-31', current_timestamp),
(-3, -3, 'NÃO SE APLICA', 'NÃO SE APLICA', current_date, '9999-12-31', current_timestamp)
---------------------

------- DIMENSÃO PROPOSIÇÃO -------
CREATE TABLE gold.dim_proposicao
(
  "sk_proposicao" int generated by default as identity not null,
  "id_proposicao" int not null,
  "sg_tipo_proposicao" text not null,
  "ds_tipo_proposicao" text not null,
  "ds_situacao"text not null,
  "dt_inicio_vigencia" date not null default current_date,
  "dt_fim_vigencia" date not null default '9999-12-31',
  "dh_ingestao" timestamp without time zone not null default current_timestamp,
  constraint dim_proposicao_pkey primary key (sk_proposicao)
) TABLESPACE pg_default;

/* INSERE REGISTROS DE CHAVE SUBSTITUTA DE DIMENSÃO */
INSERT INTO gold.dim_proposicao
("sk_proposicao" , "id_proposicao", "sg_tipo_proposicao", "ds_tipo_proposicao", ds_situacao, "dt_inicio_vigencia" , "dt_fim_vigencia", "dh_ingestao")
VALUES
(-1, -1, 'NÃO INFORMADO', 'NÃO INFORMADO', 'NÃO INFORMADO', current_date, '9999-12-31', current_timestamp),
(-3, -3, 'NÃO SE APLICA', 'NÃO SE APLICA', 'NÃO SE APLICA', current_date, '9999-12-31', current_timestamp)
-----------------------------------

------- DIMENSÃO VOTAÇÃO -------
CREATE TABLE gold.dim_votacao
(
  "sk_votacao" int generated by default as identity not null,
  "id_votacao" int not null,
  "ds_votacao" text not null,
  "ds_resultado" text not null,
  "dt_inicio_vigencia" date not null default current_date,
  "dt_fim_vigencia" date not null default '9999-12-31',
  "dh_ingestao" timestamp without time zone not null default current_timestamp,
  constraint dim_votacao_pkey primary key (sk_votacao)
) TABLESPACE pg_default;

/* INSERE REGISTROS DE CHAVE SUBSTITUTA DE DIMENSÃO */
INSERT INTO gold.dim_votacao
("sk_votacao" , "id_votacao", "ds_votacao", "ds_resultado", "dt_inicio_vigencia" , "dt_fim_vigencia", "dh_ingestao")
VALUES
(-1, -1, 'NÃO INFORMADO', 'NÃO INFORMADO', current_date, '9999-12-31', current_timestamp),
(-3, -3, 'NÃO SE APLICA', 'NÃO SE APLICA', current_date, '9999-12-31', current_timestamp)
--------------------------------

----- FATO PROPOSICAO -----
CREATE TABLE gold.ft_proposicao 
(
  "sk_deputado" int not null,
  "sk_orgao" int not null,
  "sk_proposicao" int not null,
  "sk_data_proposicao" int not null,
  "qtd_proposicao" int not null,
  "dh_ingestao" timestamp without time zone not null default current_timestamp,
  constraint ft_proposicao_pkey primary key (sk_deputado, sk_orgao, sk_proposicao, sk_data_proposicao)
) TABLESPACE pg_default;
---------------------

------ FATO VOTO ------
CREATE TABLE gold.ft_voto 
(
  "sk_votacao" int not null,
  "sk_deputado" int not null,
  "sk_orgao" int not null,
  "sk_evento" int not null,
  "sk_data_voto" int not null,
  "sk_proposicao" int not null, 
  "tp_voto" text not null, -- dimensão degenerada (DD)
  "qtd_voto" int not null,
   "dh_ingestao" timestamp without time zone not null default current_timestamp,
   constraint ft_voto_pkey primary key (sk_votacao, sk_deputado, sk_orgao, sk_evento, sk_data_voto, sk_proposicao, tp_voto)
) TABLESPACE pg_default; 
-----------------------

------ FATO DESPESA ------
CREATE TABLE gold.ft_despesa 
(
  "sk_deputado" int not null,  
  "sk_data_despesa" int not null,
  "tp_despesa" text not null, -- dimensão degenerada (DD)
  "vl_bruto" decimal not null ,
  "vl_liquido" decimal not null,
  "vl_glosa" decimal not null,
  "nr_parcela" int not null,
  "dh_ingestao" timestamp without time zone not null default current_timestamp,
  constraint ft_despesa_pkey primary key (sk_deputado, sk_data_despesa, tp_despesa)
) TABLESPACE pg_default; 
--------------------------


